#undef TEST_BEGIN
#undef TEST_END
#undef PRINT
#undef PRINTF
#undef PAUSE
#undef PAUSEF
#undef PRINT_HEADING
#undef PRINT_LINE
#undef PRINT_TIME
#undef PRINT_TYPE
#undef PRINT_SOCKET
#undef PRINT_SOCKET_OBJ
#undef PRINT_BSQ
#undef PRINT_OBJ
#undef PRINT_TOBJ
#undef PRINT_FUNCTION
#undef PRINTLN
#undef PRINT_FUNCTION_LINE
#undef SOCKET_SAVE
#undef CHECK
#undef DCHECK
#undef RCHECK
#undef COMPARE
#undef DCOMPARE
#undef RCOMPARE
#undef ASSERT
#undef DASSERT
#undef RASSERT
#undef AVOW
#undef DAVOW
#undef RAVOW
#undef RETURN
#undef DRETURN
#undef RRETURN
#undef RETURN_VALUE
#undef DRETURN_VALUE
#undef RRETURN_VALUE